// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef Main_h
#define Main_h
#include <FL/Fl.H>
#include "SciCalc.h"
#include "../include/single.h"
int main(int ac,char **av);
#endif
