// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "Main.h"

int main(int ac,char **av) {
  SingletonProcess singleton(5555);
  if (!singleton())
  {
    return 1;
  }
  SciCalc *calc = new SciCalc();
  return calc->run();
}
