// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "StaticText.h"
#include <FL/fl_draw.H>
#include <stdio.h>

StaticText::StaticText(int xx,int yy,int ww,int hh) : Fl_Widget(xx,yy,ww,hh,0) {
  str = 0;
}

StaticText::~StaticText() {
  if (str != 0) delete [] str;
}

void StaticText::value(const char *mstr) {
  int i,l;
  
  for (l=0; l<MaxLength-1;l++)
  {
    if (mstr[l] == 0) break;
  }
  if (str)
    delete [] str;
  
  str = 0;
  
  if (l == 0)
    return;
  
  str = new char[l+1];
  
  for (i=0;i<l;i++)
    str[i] = mstr[i];
  
  str[l] = 0;
}

void StaticText::draw() {
  int xx,yy,ww,hh;
  
  	draw_box();
  	xx = x() + 3;
  	yy = y() + 3;
  	ww = w() - 6;
  	hh = h() - 6;
  	fl_clip(xx,yy,ww,hh);
  	fl_color(labelcolor());
  	fl_font(labelfont(),labelsize());
  	if (str != 0)
  		fl_draw((const char *)str,xx,yy,ww,hh,align());
  	fl_pop_clip();
}
