#!/bin/bash
ME="Israel Dahl"
basedir="${PWD}"
srcdir="${basedir}/src/"
fltkdir="${basedir}/fltk/"
outputdir="${basedir}/po"
[[ -d "${outputdir}" ]] || mkdir -p "${outputdir}"
programminglanguage="c++"
defaultdomain="torios-binary"
packagename="$defaultdomain"
comments="//"
pofile="${packagename}.pot"

xgettext -c --copyright-holder="\"$ME\"" -p "$outputdir" --strict --default-domain="$defaultdomain" --package-name="\"$packagename\"" --output "${outputdir}/${pofile}" --c++ --package-version=$verno about/*.cxx askpass/*.cxx pm-dialogs/*.cxx run/*.cxx apt/*.cxx text/*.cxx screenie/*.cxx image/*.cxx calc/*.cxx welcome/*.cxx fm/*.cxx
sed -i 's/CHARSET/UTF-8/' "${outputdir}/${pofile}"

cd "${basedir}"
echo "Generating the locales"
for locale in "$outputdir/"**.po
do
  if [[ -f "$locale" ]]
  then
    echo $locale
    DIR="${locale/*\/}"
    DIR="${DIR/.po}"
    DIR="$basedir/usr/share/locale/$DIR/LC_MESSAGES/"
    [[ -d "$DIR" ]] || mkdir -p "$DIR"
    msgfmt -o "$defaultdomain.mo" "$locale"
    mv "$defaultdomain.mo" "$DIR"
  fi
done
echo "Done"
