// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flcalendar_h
#define flcalendar_h
#include <FL/Fl.H>
#include <Fl/Fl_Preferences.H>
#include "../include/functions.h"
#include "../include/Fl_Functions.h"
#include "../include/Fl_Calendar.H"
#include <iostream>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Input.H>

class UI {
public:
  Fl_Double_Window* date_window();
  Fl_Double_Window *date_win;
  Fl_Calendar *cal;
private:
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
  inline void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
public:
  Fl_Double_Window* settings_window();
private:
  inline void cb_Background_i(Fl_Button*, void*);
  static void cb_Background(Fl_Button*, void*);
  inline void cb_Highlight_i(Fl_Button*, void*);
  static void cb_Highlight(Fl_Button*, void*);
  inline void cb_Label_i(Fl_Button*, void*);
  static void cb_Label(Fl_Button*, void*);
public:
  Fl_Slider *ls_slide;
private:
  inline void cb_ls_slide_i(Fl_Slider*, void*);
  static void cb_ls_slide(Fl_Slider*, void*);
public:
  Fl_Value_Input *ls_out;
private:
  inline void cb_ls_out_i(Fl_Value_Input*, void*);
  static void cb_ls_out(Fl_Value_Input*, void*);
  inline void cb_SAVE_i(Fl_Button*, void*);
  static void cb_SAVE(Fl_Button*, void*);
public:
  void get_pref();
  void save_pref();
};
#endif
