// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef flabout_h
#define flabout_h
#include <FL/Fl.H>
#include <string>
#include <iostream>
#include <sys/stat.h>
#include <sys/types.h>
#include <algorithm>
#include <dirent.h> //dir
#include <fstream> //ifstream
#include <fcntl.h> //readlink
#include <unistd.h> //readlink
#include <vector>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Browser.H>

class UI {
public:
  std::string MSG; 
  std::string combine(std::vector<std::string> in);
  std::string file_to_string(std::string filename);
  std::string get_directory_from_filename(std::string filename);
  std::string get_symlinkpath(std::string symlink);
  void make_text();
  Fl_Double_Window* make_window();
  Fl_Double_Window *about;
  Fl_Button *ok;
private:
  inline void cb_ok_i(Fl_Button*, void*);
  static void cb_ok(Fl_Button*, void*);
public:
  Fl_Browser *text;
  void populateBrowserWithString(Fl_Browser *o, std::string STRING);
  bool test_file(std::string fileWithFullPATH);
  std::string toriosversion();
};
int main(int argc, char*argv[]);
void trace(std::string msg);
#endif
