// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flaskpass_h
#define flaskpass_h
#include <FL/Fl.H>
#include "../include/toolbar_icons.h"
#include <string>
#include <iostream>
#include <vector>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>

class UI {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *passwin;
  Fl_Input *password;
private:
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
public:
  Fl_Button *ok;
private:
  inline void cb_ok_i(Fl_Button*, void*);
  static void cb_ok(Fl_Button*, void*);
public:
  std::string combine(std::vector<std::string> in);
  std::string MSG; 
};
int main(int argc, char*argv[]);
#endif
