// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flrun_h
#define flrun_h
#include <FL/Fl.H>
#include "../include/functions.h"
#include "../include/single.h"
#include <stdexcept>
#include <string>
#include <iostream>
#include <fstream>
#include <vector>
#include <sys/stat.h>
#include <sys/types.h>
#include <fcntl.h>
#include <sys/sendfile.h>  // sendfile
#include <algorithm>
#include <float.h>
#include <sstream>
#include <float.h>
#include <dirent.h>
#include <sys/stat.h>
#include <langinfo.h>
#include <stdlib.h>
#include <stdio.h>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <errno.h>
#include <locale.h>
#include <unistd.h>
#include <signal.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class UI {
public:
  Fl_Double_Window* make_window();
  Fl_Input *run_input;
private:
  inline void cb_run_input_i(Fl_Input*, void*);
  static void cb_run_input(Fl_Input*, void*);
  inline void cb_OK_i(Fl_Button*, void*);
  static void cb_OK(Fl_Button*, void*);
};
int main(int argc, char *argv[]);
int usage(char* name);
#endif
